version: '3'
services:
  jenkins:
    user: root
    image: jenkins/docker
    build:
      context: dockerjenkins
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    privileged: true
    user: root
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net
  postgres:
    image: postgres:14
    networks:
      - net
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonarpasswd
    volumes:
      - $PWD/postgres-data:/var/lib/postgresql/data
  sonarqube:
    image: sonarqube:lts
    platform: linux/amd64
    ports:
      - 9000:9000
      - 9092:9092
    networks:
      - net
    environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonarpasswd
      SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres:5432/sonar"
    depends_on: 
      - postgres

networks:
  net:
